---
workflow:
  rules:
    # Do not allow manually triggered pipelines to prevent duplicates!
    # Instead re-run the pipeline created with the last push
    - if: $CI_PIPELINE_SOURCE != "push"
      when: never
    # Only execute when a valid, semantic-versioned tag is given.
    # Examples: v1.0.0  |  v1.0.0-RC3  |  v0.5.0-alpha
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+[.][0-9]+[.][0-9]+(-[a-zA-Z0-9]+)?$/
    - if: $CI_COMMIT_BRANCH

default:
  interruptible: true

stages:
  - build

container:build:
  stage: build
  image: quay.io/containers/buildah
  variables:
    TAG: zed-rocky-9
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah build -t $CI_PROJECT_NAME:$TAG
    - buildah tag $CI_PROJECT_NAME:$TAG $CI_REGISTRY_IMAGE:$TAG
    - buildah push $CI_REGISTRY_IMAGE:$TAG
