---
default:
  interruptible: true

stages:
  - build

container:build:
  stage: build
  image: docker.io/docker:dind
  variables:
    TAG: zed-rocky-9
  script:
    - apk add py3-pip
    - pip install --no-input 'kolla==15.1.0'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - kolla-build --config-file kolla-build.conf
    - docker push kolla/magnum-conductor:$TAG
