---
name: Kolla Build
description: "Installs, configures, and runs Kolla Build."

inputs:
  component:
    description: "Name of the component to build."
    required: true
  ghcr_token:
    description: "Token for accessing GitHub Container Registry."
    required: true

runs:
  using: "composite"
  steps:
    - name: Ensure pip is installed
      run: sudo apt install -y python3-pip
      shell: bash

    - name: Install Kolla
      run: pip install --no-input 'docker' 'kolla==17.3.0'
      shell: bash

    - name: Set registry namespace in kolla-build config file
      run: >
        sed -i 's|<registry-namespace>|${{ github.repository }}|'
        ${{ inputs.component }}/build.conf
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}

    - name: Build and push containers
      run: >
        kolla-build
        --config-file ${{ inputs.component }}/build.conf
        --template-override ${{ inputs.component }}/override.j2
      shell: bash
