---
name: "Setup Kolla"
description: "Installs and configures Kolla"

inputs:
  component:
    description: "Name of the component to build"
    required: true

runs:
  using: "composite"
  steps:
    - name: Ensure pip is installed
      run: sudo apt install -y python3-pip
      shell: bash

    - name: Install Kolla
      run: pip install --no-input 'docker' 'kolla==17.3.0'
      shell: bash

    - name: Set registry namespace in config file
      run: >
        sed -i 's|<registry-namespace>|${{ github.repository }}|'
        ${{ inputs.component }}/build.conf
      shell: bash
