---
name: Build Magnum

on:
  push:
    paths:
      - 'magnum/**'
  workflow_dispatch:
    # inputs:
    #   profile:
    #     description: 'Profile to build'
    #     required: true

env:
  COMPONENT: "magnum"
  # BRANCH: "${{ github.event.inputs.branch }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure pip is installed
        run: sudo apt install -y python3-pip

      - name: Install Kolla
        run: pip install --no-input 'docker' 'kolla==17.3.0'

      - name: Set container tag in config file
        run: >
          sed -i 's|<registry-namespace>|${{ github.repository }}|'
          kolla-build.conf

      - name: Build container(s)
        run: >
          kolla-build
          --config-file kolla-build.conf
          --template-override ${{ env.COMPONENT }}/override.j2
          --profile ${{ env.COMPONENT }}
