---
name: Build Magnum

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Remote branch'
        required: true
        default: 'stable/zed'

env:
  COMPONENT: magnum
  REGISTRY: ghcr.io
  BRANCH: "${{ github.event.inputs.branch }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set 'TAG' environment variable
        run: echo "TAG=$(echo ${{ env.BRANCH }} | sed 's|/|-|')" >> $GITHUB_ENV

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure pip is installed
        run: sudo apt install -y python3-pip

      - name: Install Kolla
        run: pip install --no-input 'kolla==15.1.0'

      - name: Set remote Git ref in config file
        run: >
          sed -i 's|<${{ env.COMPONENT }}-gitref>|${{ env.BRANCH }}|'
          ${{ env.COMPONENT }}.conf

      - name: Set container tag in config file
        run: >
          sed -i 's|<${{ env.COMPONENT }}-tag>|${{ env.TAG }}|'
          ${{ env.COMPONENT }}.conf

      - name: Build container(s)
        run: kolla-build --config-file ${{ env.COMPONENT }}.conf

      - name: Tag the magnum-api image
        run: >
          docker tag
          kolla/magnum-api:${{ env.TAG }}
          ghcr.io/${{ github.repository }}/magnum-api:${{ env.TAG }}

      - name: Tag the magnum-conductor image
        run: >
          docker tag
          kolla/magnum-conductor:${{ env.TAG }}
          ghcr.io/${{ github.repository }}/magnum-conductor:${{ env.TAG }}

      - name: Push magnum-api image
        run: docker push ghcr.io/${{ github.repository }}/magnum-api:${{ env.TAG }}

      - name: Push magnum-conductor image
        run: docker push ghcr.io/${{ github.repository }}/magnum-conductor:${{ env.TAG }}
