---
name: Build Magnum

on:
  push:
    paths:
      - '.github/actions/setup-kolla/**'
      - 'magnum/**'

env:
  COMPONENT: "magnum"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Kolla
        uses: ./.github/actions/setup-kolla
        with:
          component: ${{ env.COMPONENT }}

      - name: Build container(s)
        run: >
          kolla-build
          --config-file ${{ env.COMPONENT }}/build.conf
          --template-override ${{ env.COMPONENT }}/override.j2
