---
name: Build Magnum

on:
  push:
    paths:
      - '.github/actions/setup-kolla/**'
      - 'magnum/**'

env:
  COMPONENT: "magnum"

jobs:
  kolla-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Kolla
        uses: ./.github/actions/kolla-build
        with:
          component: ${{ env.COMPONENT }}
